export const RouteIndex = '/'
export const RouteSignup = '/signup'
export const RouteSignin = '/signin'
export const RouteProfile = '/profile'
export const RouteCategoryDetails = '/categories'
export const RouterAddCategory = '/categories/add'
export const RouterEditCategory = '/categories/edit'
